create table if not exists public.dieta (
  id bigint generated by default as identity primary key,
  state jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.dieta
add column if not exists state jsonb not null default '{}'::jsonb;

alter table public.dieta
add column if not exists updated_at timestamptz not null default now();

alter table public.dieta enable row level security;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_dieta_updated_at on public.dieta;
create trigger set_dieta_updated_at
before update on public.dieta
for each row
execute function public.set_updated_at();

drop policy if exists "public le plano" on public.dieta;
create policy "public le plano"
on public.dieta
for select
to anon, authenticated
using (id = 1);

drop policy if exists "public cria plano" on public.dieta;
create policy "public cria plano"
on public.dieta
for insert
to anon, authenticated
with check (id = 1);

drop policy if exists "public atualiza plano" on public.dieta;
create policy "public atualiza plano"
on public.dieta
for update
to anon, authenticated
using (id = 1)
with check (id = 1);

insert into public.dieta (id, state)
values (1, '{}'::jsonb)
on conflict do nothing;
